# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/leijurv/Dropbox/2018-Field

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/leijurv/Dropbox/2018-Field

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.5/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.9.5/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/leijurv/Dropbox/2018-Field/CMakeFiles /Users/leijurv/Dropbox/2018-Field/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/leijurv/Dropbox/2018-Field/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named field

# Build rule for target.
field: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 field
.PHONY : field

# fast build rule for target.
field/fast:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/build
.PHONY : field/fast

botlocale/mcl.o: botlocale/mcl.cpp.o

.PHONY : botlocale/mcl.o

# target to build an object file
botlocale/mcl.cpp.o:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/botlocale/mcl.cpp.o
.PHONY : botlocale/mcl.cpp.o

botlocale/mcl.i: botlocale/mcl.cpp.i

.PHONY : botlocale/mcl.i

# target to preprocess a source file
botlocale/mcl.cpp.i:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/botlocale/mcl.cpp.i
.PHONY : botlocale/mcl.cpp.i

botlocale/mcl.s: botlocale/mcl.cpp.s

.PHONY : botlocale/mcl.s

# target to generate assembly for a file
botlocale/mcl.cpp.s:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/botlocale/mcl.cpp.s
.PHONY : botlocale/mcl.cpp.s

bottracking/bottrack.o: bottracking/bottrack.cpp.o

.PHONY : bottracking/bottrack.o

# target to build an object file
bottracking/bottrack.cpp.o:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/bottracking/bottrack.cpp.o
.PHONY : bottracking/bottrack.cpp.o

bottracking/bottrack.i: bottracking/bottrack.cpp.i

.PHONY : bottracking/bottrack.i

# target to preprocess a source file
bottracking/bottrack.cpp.i:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/bottracking/bottrack.cpp.i
.PHONY : bottracking/bottrack.cpp.i

bottracking/bottrack.s: bottracking/bottrack.cpp.s

.PHONY : bottracking/bottrack.s

# target to generate assembly for a file
bottracking/bottrack.cpp.s:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/bottracking/bottrack.cpp.s
.PHONY : bottracking/bottrack.cpp.s

darknet/network.o: darknet/network.cpp.o

.PHONY : darknet/network.o

# target to build an object file
darknet/network.cpp.o:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/darknet/network.cpp.o
.PHONY : darknet/network.cpp.o

darknet/network.i: darknet/network.cpp.i

.PHONY : darknet/network.i

# target to preprocess a source file
darknet/network.cpp.i:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/darknet/network.cpp.i
.PHONY : darknet/network.cpp.i

darknet/network.s: darknet/network.cpp.s

.PHONY : darknet/network.s

# target to generate assembly for a file
darknet/network.cpp.s:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/darknet/network.cpp.s
.PHONY : darknet/network.cpp.s

field.o: field.cpp.o

.PHONY : field.o

# target to build an object file
field.cpp.o:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/field.cpp.o
.PHONY : field.cpp.o

field.i: field.cpp.i

.PHONY : field.i

# target to preprocess a source file
field.cpp.i:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/field.cpp.i
.PHONY : field.cpp.i

field.s: field.cpp.s

.PHONY : field.s

# target to generate assembly for a file
field.cpp.s:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/field.cpp.s
.PHONY : field.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/main.cpp.s
.PHONY : main.cpp.s

objects.o: objects.cpp.o

.PHONY : objects.o

# target to build an object file
objects.cpp.o:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/objects.cpp.o
.PHONY : objects.cpp.o

objects.i: objects.cpp.i

.PHONY : objects.i

# target to preprocess a source file
objects.cpp.i:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/objects.cpp.i
.PHONY : objects.cpp.i

objects.s: objects.cpp.s

.PHONY : objects.s

# target to generate assembly for a file
objects.cpp.s:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/objects.cpp.s
.PHONY : objects.cpp.s

objecttracking/cubetrack.o: objecttracking/cubetrack.cpp.o

.PHONY : objecttracking/cubetrack.o

# target to build an object file
objecttracking/cubetrack.cpp.o:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/objecttracking/cubetrack.cpp.o
.PHONY : objecttracking/cubetrack.cpp.o

objecttracking/cubetrack.i: objecttracking/cubetrack.cpp.i

.PHONY : objecttracking/cubetrack.i

# target to preprocess a source file
objecttracking/cubetrack.cpp.i:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/objecttracking/cubetrack.cpp.i
.PHONY : objecttracking/cubetrack.cpp.i

objecttracking/cubetrack.s: objecttracking/cubetrack.cpp.s

.PHONY : objecttracking/cubetrack.s

# target to generate assembly for a file
objecttracking/cubetrack.cpp.s:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/objecttracking/cubetrack.cpp.s
.PHONY : objecttracking/cubetrack.cpp.s

vision.o: vision.cpp.o

.PHONY : vision.o

# target to build an object file
vision.cpp.o:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/vision.cpp.o
.PHONY : vision.cpp.o

vision.i: vision.cpp.i

.PHONY : vision.i

# target to preprocess a source file
vision.cpp.i:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/vision.cpp.i
.PHONY : vision.cpp.i

vision.s: vision.cpp.s

.PHONY : vision.s

# target to generate assembly for a file
vision.cpp.s:
	$(MAKE) -f CMakeFiles/field.dir/build.make CMakeFiles/field.dir/vision.cpp.s
.PHONY : vision.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... field"
	@echo "... botlocale/mcl.o"
	@echo "... botlocale/mcl.i"
	@echo "... botlocale/mcl.s"
	@echo "... bottracking/bottrack.o"
	@echo "... bottracking/bottrack.i"
	@echo "... bottracking/bottrack.s"
	@echo "... darknet/network.o"
	@echo "... darknet/network.i"
	@echo "... darknet/network.s"
	@echo "... field.o"
	@echo "... field.i"
	@echo "... field.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... objects.o"
	@echo "... objects.i"
	@echo "... objects.s"
	@echo "... objecttracking/cubetrack.o"
	@echo "... objecttracking/cubetrack.i"
	@echo "... objecttracking/cubetrack.s"
	@echo "... vision.o"
	@echo "... vision.i"
	@echo "... vision.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

